# Fly.io deployment configuration
# Deploy with: flyctl deploy

app = "causal-memory-core"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/app/data/causal_memory.db"
  LLM_MODEL = "gpt-3.5-turbo"
  SIMILARITY_THRESHOLD = "0.7"
  MAX_POTENTIAL_CAUSES = "5"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = "causal_memory_data"
  destination = "/app/data"
